export const randomWords = [
    "abacá", "abismo", "abnegación", "abono", "abrazo", "acantilado", "acerico", "acierto", "alabanza", 
    "alea", "alegría", "aliento", "amor", "amparo", "anhelado", "ansia", "aprecio", "árbol", "arboleda", 
    "ardor", "armonía", "arrullo", "abrazo", "arena", "arrepentido", "aseo", "asombro", "asustar", "ático", 
    "avidez", "azar", "actitud", "banquete", "barro", "barrera", "base", "batir", "belleza", "bisiesto", 
    "brillante", "botella", "bombón", "calidez", "cámara", "caridad", "carnicero", "cerveza", "círculo", 
    "cielo", "claro", "compañía", "consejo", "corazón", "cumbre", "corriente", "corriente", "corriente", 
    "creatividad", "cuaderno", "dado", "dance", "danza", "decoro", "deporte", "derivar", "desbordar", 
    "descansar", "deslizar", "deseo", "destello", "dictadura", "diluvio", "dilema", "doctor", "dolor", 
    "duende", "educación", "elixir", "emocionante", "equilibrio", "escuela", "esfuerzo", "espejo", "estabilidad", 
    "estrella", "eternidad", "felicidad", "fiesta", "fiebre", "filtro", "florecer", "fotografía", "frecuencia", 
    "fugaz", "fusión", "galeón", "gato", "gente", "gimnasio", "gloria", "gracia", "herencia", "hoja", "horizonte", 
    "huevo", "humo", "ideal", "imagen", "inspiración", "intensidad", "invierno", "jirafa", "jugar", "juguete", 
    "juicio", "laurel", "luz", "madurez", "mágico", "mamá", "manantial", "manteca", "mar", "mayo", "meditación", 
    "melancolía", "memoria", "mentalidad", "místico", "monte", "navegar", "neón", "nieve", "noche", "nubes", 
    "observación", "oceano", "olvidar", "optimismo", "orgullo", "paz", "pequeño", "perdón", "planeta", "poder", 
    "pregunta", "presencia", "primavera", "progreso", "proyecto", "química", "reconocimiento", "revolución", 
    "risa", "rojo", "sabiduría", "sagrado", "salud", "sangre", "secreto", "serpiente", "silencio", "sonrisa", 
    "tarde", "temor", "terremoto", "teoría", "tormenta", "tostada", "tradición", "universo", "vacío", "valiente", 
    "viento", "violeta", "volcán", "voluntad", "vuelo", "yoga", "zafiro", "zombie", "zona", "zapato", "aceite", 
    "acercar", "acidez", "afán", "agobio", "alquiler", "aprobación", "banco", "barrera", "basura", "básico", 
    "bebé", "belleza", "bicicleta", "blanco", "boca", "bosque", "caja", "calor", "cama", "cambio", "campo", 
    "candidato", "capítulo", "carro", "carta", "catar", "cena", "cierre", "coche", "colina", "comida", "compañero", 
    "consejo", "corral", "crecer", "cuadro", "debate", "decidir", "derecho", "despacho", "despertar", "deseo", 
    "dificultad", "dinero", "doblar", "doctor", "dolor", "espejo", "familia", "felicidad", "futuro", "gafas", 
    "gente", "grande", "grasa", "hielo", "hogar", "hombre", "igualdad", "inmortal", "interés", "ironía", "isla", 
    "juguete", "karma", "laurel", "leyenda", "limón", "luna", "madre", "mamá", "marco", "mundo", "navegar", 
    "necesidad", "nube", "ocultar", "orificio", "panal", "pantalla", "peligro", "pensar", "persona", "pluma", 
    "poder", "progreso", "rojo", "sabor", "seguro", "silencio", "sol", "sombra", "teoría", "terreno", "tierra", 
    "tiempo", "universo", "vaca", "vela", "vida", "viento", "volar", "zafiro", "zapato", "zebra", "zona"
  ];